Implement a new design
viskan/streamline-express-page pull request #8
Opened 2017-08-03 11:36 UTC by gillstrom

Also changed name to `Streamline Express` and included @anton-johansson's Klarna Recurring part.

2017-08-03 12:30 UTC, anton-johansson requested changes

2017-08-03 12:30 UTC, anton-johansson commented on package-lock.json
> +  "name": "estore-express-page",
```diff
-  "name": "estore-express-page",
+  "name": "streamline-express-page",
```

I get this as soon as I run `npm install` :)

2017-08-03 12:32 UTC, gillstrom commented on package-lock.json
> +  "name": "estore-express-page",
Oh..

2017-08-03 12:33 UTC, gillstrom commented on package-lock.json
> +  "name": "estore-express-page",
FixeD

2017-08-03 12:34 UTC, anton-johansson approved these changes

2017-08-03 12:34 UTC, merged

2017-08-03 19:12 UTC, kevva commented
:+1:

2017-08-03 19:18 UTC, kevva commented on source/se/failure.html
> +				<p>Gå tillbaka till vår beställningssidan och testa igen.</p>
> Gå tillbaka till vår beställningssidan och testa igen.

Shouldn't it be `Gå tillbaka till vår beställningssida` or `Gå tillbaka till bestälningssidan`?

2017-08-03 19:18 UTC, kevva commented on source/klarna-recurring/index.html
> +		<!--[if lt IE 8]>
Is this even necessary anymore?

2017-08-03 19:18 UTC, kevva commented on source/se/success.html
> +				<p>En orderbekräftelse kommer inom kort komma på epost.</p>
`En orderbekräftelse kommer inom kort skickas till din e-post.`?

2017-08-04 06:35 UTC, anton-johansson commented on source/se/failure.html
> +				<p>Gå tillbaka till vår beställningssidan och testa igen.</p>
Thanks, fixed in 6b7b67a47538cea2318818c5939df154f76e4056.

2017-08-04 06:36 UTC, anton-johansson commented on source/se/success.html
> +				<p>En orderbekräftelse kommer inom kort komma på epost.</p>
Thanks, fixed in 6b7b67a47538cea2318818c5939df154f76e4056.

2017-08-04 06:36 UTC, anton-johansson commented on source/klarna-recurring/index.html
> +		<!--[if lt IE 8]>
I wouldn't know. :(

2017-08-04 07:29 UTC, gillstrom commented on source/klarna-recurring/index.html
> +		<!--[if lt IE 8]>
Probably not no..